
' 
' class diagram styles
'
'-- choose local or repo; commenting out one or the other
!includeurl https://raw.githubusercontent.com/privafy/UsePlantUML/master/dist/Common.puml
'include ../dist/Common.puml

skinparam Class {
    BackgroundColor        PVLTGREEN
    BorderColor            PDKGREEN
    ArrowColor             BLACK
}
skinparam Rectangle {
    BackgroundColor        PVLTGREEN
    BorderColor            PDKGREEN
    ArrowColor             BLACK
}
skinparam Arrow {
    Color     PDKGREEN
    FontColor PAPURPLE
    Thickness 2
}
skinparam Note {
    BackgroundColor PVLTGREEN
    BorderColor     PGLTGRAY2
    FontColor       PGLTGRAY3
}

skinparam Collections {
    BackgroundColor PVLTGREEN
    BorderColor     PGLTGRAY2
    FontColor       PGLTGRAY3
}
    
skinparam Cloud {
    'BackgroundColor PVLTGREEN
    BorderColor     PDKGREEN
    FontColor       PGLTGRAY3
}
  
